### ISSUE TITLE
getting issues 503 for nginx 

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [Email-Dashboard/Email-Dashboard#24]
503 Service Temporarily Unavailable
nginx/1.14.0

**Comment by muhammet** [comment]
Is your domain in the `docker-compose.yml`

**Comment by medicharlachiranjeevi** [comment]
Nope localdomain

**Comment by medicharlachiranjeevi** [comment]
now i have put my domain in the .env same error

**Comment by muhammet** [comment]
Hi @medicharlachiranjeevi ,

according  the `docker-compose.ym` we are using subdomain.

![image](https://user-images.githubusercontent.com/989759/46647429-9d571e80-cb98-11e8-80dd-3bcacf08532b.png)

**Comment by muhammet** [comment]
@medicharlachiranjeevi any updates ?

**Comment by muhammet** [comment]
Closing due the inactivity.
