### ISSUE TITLE
Unable to load application:

### ISSUE THREAD

**Issue by medicharlachiranjeevi** [Email-Dashboard/Email-Dashboard#29]
Unable to load application: I18n::InvalidLocaleData: can not load translations from /rails-dashboard/config/locales/devise.zh-CN.yml: #<Psych::SyntaxError: (/rails-dashboard/config/locales/devise.zh-CN.yml): found character that cannot start any token while scanning for the next token at line 68 column 20>
web_1          | /usr/local/bundle/gems/i18n-0.9.5/lib/i18n/backend/base.rb:232:in `rescue in load_yml': can not load translations from /rails-dashboard/config/locales/devise.zh-CN.yml: #<Psych::SyntaxError: (/rails-dashboard/config/locales/devise.zh-CN.yml): found character that cannot start any token while scanning for the next token at line 68 column 20> (I18n::InvalidLocaleData)

**Comment by muhammet** [comment]
@medicharlachiranjeevi looking into it.
